version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  build:
    docker:
      - image: python

    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: Run main1.py
          command: python main1.py

  test:
    docker:
      - image: python
    steps:
      - checkout
      - run:
          name: Run test.py
          command: python test.py

# Orchestrate jobs using workflows
workflows:
  build_and_test:
    jobs:
      - build
      - test
